scenario: lade
n_frame: 80
n_requested_frame: 60
n_node: 40
n_courier: 20
n_station: 6
n_drone: 10
min_direct_dist: 10

n_init_requests: 20
n_norm_requests: 200
max_consider_requests: -1

max_capacity: 5
dist_distribution: 2D
max_dist: 10
n_node_tot: 144

dist_cost_drone: 0.3
dist_cost_courier: 0.2
dist_req_profit: 1

seed: 1
seed_env: 1
info_batch_size: 0
debug: False

